server:
  port: 8080

logging:
  level:
    org.springframework.security: debug
    pe.com.ocmf.oauth2: debug

spring:
  application:
    name: oauth2-client
  security:
    oauth2:
      client:
        registration:
          my-ocmf-client:
            provider: oauth2-server
            client-id: my-ocmf-client
            client-secret: passw0rd
            authorization-grant-type: client_credentials
            scope: read,write
        provider:
          oauth2-server:
            issuer-uri: http://localhost:9000